### ISSUE TITLE
satstack stops suddenly stops while imporing descriptors

### ISSUE THREAD

**Issue by Zordss** [LedgerHQ/satstack#107]
HI,

I am trying to connect my ledger live to my full node and am running satstack.
But I am getting the error below:
Begin*******************************************************

[2023/04/15 - 20:29:46]  INFO worker: Importing descriptors                         duration=28m0s progress=0.69%
[GIN] 2023/04/15 - 20:29:46 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:47 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:48 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:49 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:50 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:51 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:52 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:53 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:54 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[2023/04/15 - 20:29:55]  INFO worker: Importing descriptors                         duration=28m8s progress=0.70%
[GIN] 2023/04/15 - 20:29:55 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:56 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:57 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:29:58 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:30:00 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:30:01 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:30:02 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[GIN] 2023/04/15 - 20:30:03 | 200 |            0s |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"
[2023/04/15 - 20:30:03] ERROR worker: Failed to query wallet state                  error=status code: 403, response: ""
[2023/04/15 - 20:30:03] FATAL worker: Failed to send INTERRUPT signal               error=not supported by windows pid=5476

***********************************************************END

I can restart the service and it will run for a few minutes but comes back with the same error again?
can someone please help me understand what this means and how I can fix it?

**Comment by oullec** [comment]
Which version of ledger live do you have ? This is not compatible with ledger live 2.54 and more…
I had the same issue and downgraded ledger live to 2.52 solved my issue

**Comment by oullec** [comment]
From : https://github.com/LedgerHQ/satstack
![image](https://user-images.githubusercontent.com/99608050/232218238-7039c575-c9e2-48d3-8cc5-5f0077070ae7.png)

and also : 
https://github.com/LedgerHQ/satstack/issues/105

**Comment by Zordss** [comment]
Thank you for the comment.
I have 2.54.
It seems even though I get the error, substack actually continues to sync in the background so now the progress is at around 1.95%. Once, the progress finishes I will try to connect on ledger live v2.54 again and if that doesn't work, will downgrade to 2.52 and see how it goes.

**Comment by oullec** [comment]
As mention : 2.54 is not working with Satstack.
Good luck :-)
