### ISSUE TITLE
FATAL Failed to initialize Bus                      error=failed to load wallet: -35: Wallet "satstack" is already loaded.

### ISSUE THREAD

**Issue by krakenbait** [LedgerHQ/satstack#138]
Why are you like this?

I have managed to get my Umbrel Bitcoin Node (Core v27.0.0) connected and synced exactly one time with Ledger Live (v 2.52.0). After unfortunately having to restart my MacOS (Sonoma 14.5), my .lss executable spits out the following error: 

     FATAL Failed to initialize Bus                      error=failed to load wallet: -35: Wallet "satstack" is already loaded.

How on earth do I get this program running again? I'm not resyncing a full Bitcoin node a third time just for the program to fail to launch on startup. Any advice or suggestions is appreciated.

**Comment by adrienlacombe** [comment]
run once with `--unload-wallet`, stop and start again normally

**Comment by krakenbait** [comment]
@adrienlacombe I appreciate the information. One quick follow-up question: where exactly do I insert this command? Terminal?

**Comment by DataKnox** [comment]
> run once with `--unload-wallet`, stop and start again normally

This worked for me as well, thanks

**Comment by adrienlacombe** [comment]
> @adrienlacombe I appreciate the information. One quick follow-up question: where exactly do I insert this command? Terminal?

correct, same way you start usually

**Comment by krakenbait** [comment]
@adirenlacombe Thank you for your help! I was able to get it working through the terminal.

**Comment by adrienlacombe** [comment]
> @adirenlacombe Thank you for your help! I was able to get it working through the terminal.

glad to hear that
