### ISSUE TITLE
eth balance requests being sent to satstack

### ISSUE THREAD

**Issue by xwvvvvwx** [LedgerHQ/satstack#39]
Hi, I just installed satstack and got it up and running, very happy to be able to use my full node with ledger live :slightly_smiling_face: :tada: 

When I look in the satstack logs, I see requests being made to `eth` related endpoints (e.g. `/blockchain/v3/eth/addresses/0xADDR/balance`), what exactly is happening to these requests? Are the requests forwarded to ledgers backend? Is ledger-live operating in a degraded state for non bitcoin assets if I have `EXPLORER` set to point to `satstack`?

**Comment by onyb** [comment]
@xwvvvvwx Thanks for taking satstack for a spin! 🙌

We're aware of this issue - rest assured that you won't experience this once https://github.com/LedgerHQ/ledger-live-desktop/pull/3291 is merged, which includes a native integration (easy setup, slick UX, etc) for satstack.

Let's keep this open until the official release, in case someone else runs into it.

**Comment by onyb** [comment]
Should be good with Ledger Live 2.18.0! Check out the updated usage instructions [here](https://github.com/LedgerHQ/satstack#usage) (see recommended setup).

**Comment by xwvvvvwx** [comment]
awesome! Thanks :pray: :sparkles:
