### ISSUE TITLE
Build UTXO map concurrently

### ISSUE THREAD

**Issue by onyb** [LedgerHQ/satstack#4]
The `/blockchain/v3/transactions/<txnHash>` endpoint has a lot of inefficiencies and can take ages to finish even for seemingly ordinary-looking transactions.

This is especially the case for transactions that have a lot of non-coinbase inputs, since we fetch the whole transaction resource for each `output_hash` / `output_index` pair. This maps to the `buildUtxoMap` method in the code.

The idea is to fetch the resource for each `output_hash` concurrently while building the UTXO map.

Here is how a sample HTTP request performs today:

```
0x8ad947f78e0dc41e5c5d1e0b3ba11e5cbb09ee7eaca7eec033e768474dd0ad83
```
<img width="1423" alt="Screenshot 2020-05-01 at 19 01 45" src="https://user-images.githubusercontent.com/3684187/80808928-3c5dc400-8bde-11ea-992d-ec8384ab37a3.png">

(connected to a Blockdaemon Bitcoin mainnet node)

**Comment by onyb** [comment]
### Update

While this is still a problem, running the benchmark using remote Blockdaemon nodes is not a fair way to draw conclusions about the performance of Ledger Sats Stack. A major part of the response time is spent on network latency. Additionally, Blockdaemon can throttle requests, as has been observed on the CI.

**Comment by adrienlacombe-ledger** [comment]
Not relevant anymore
