### ISSUE TITLE
FATAL Failed to initialize Bus

### ISSUE THREAD

**Issue by tooraj-enayati** [LedgerHQ/satstack#46]
I'm trying to run satstack on myNode Raspberry Pi 4.  I donwloaed go and compile it and manged to get it runing but now I get the following erro on start up. Something to do with wallet.dat already being loaded.

admin@myNode:/home/lss $ ./lss
[2021/02/13 - 02:57:55]  INFO Ledger SatStack (lss) v0.12.0                 arch=linux arm build= commit= runtime=go1.15.8
[2021/02/13 - 02:57:55]  INFO Config file detected                          path=lss.json
[2021/02/13 - 02:57:55]  INFO Warming up...
[2021/02/13 - 02:57:55] FATAL Failed to initialize Bus                      error=failed to load wallet: -4: Wallet file verification failed. Refusing to load database. Data file '/home/bitcoin/.bitcoin/satstack/wallet.dat' is already loaded.

**Comment by tooraj-enayati** [comment]
No satstack folder!

admin@myNode:/home/bitcoin/.bitcoin $ ls -al
total 187940
drwxr-xr-x  6 bitcoin bitcoin      4096 Feb 13 03:23 .
drwxr-xr-x 21 bitcoin bitcoin      4096 Feb  5 19:22 ..
-rw-------  1 bitcoin bitcoin    224355 Nov 28 08:02 banlist.dat
-rw-r--r--  1 bitcoin bitcoin       970 Feb  5 19:21 bitcoin.conf
-rw-------  1 bitcoin bitcoin         5 Feb  5 19:21 bitcoind.pid
drwxr-xr-x  3 bitcoin bitcoin    131072 Feb 12 21:30 blocks
drwxr-xr-x  2 bitcoin bitcoin    114688 Feb 13 03:10 chainstate
-rw-------  1 bitcoin bitcoin        75 Feb  5 19:21 .cookie
-rw-------  1 bitcoin bitcoin   7792060 Feb 13 03:12 debug.log
-rw-r--r--  1 bitcoin bitcoin         9 Feb  5 19:21 env
-rw-------  1 bitcoin bitcoin    247985 Feb  5 18:40 fee_estimates.dat
drwxr-xr-x  3 bitcoin bitcoin      4096 Aug 20 14:52 indexes
-rw-------  1 bitcoin bitcoin         0 Oct 20 23:00 .lock
-rw-------  1 bitcoin bitcoin 183364248 Feb  5 18:40 mempool.dat
-rw-------  1 bitcoin bitcoin       820 Feb  1 02:37 onion_private_key
-rw-------  1 bitcoin bitcoin        99 Feb  5 19:22 onion_v3_private_key
-rw-------  1 bitcoin bitcoin    513189 Feb 13 03:23 peers.dat
-rw-r--r--  1 bitcoin bitcoin         7 Feb  5 19:21 settings.json
drwx------  3 bitcoin bitcoin      4096 Feb  5 19:21 wallet.dat

**Comment by tooraj-enayati** [comment]
I have tried both ./lss and sudo ./lss

**Comment by HamishMacEwan** [comment]
Same issue here.

```
C:\Program Files\Ledger Live> .\lss.exe
[2021/03/08 - 18:43:28]  INFO Ledger SatStack (lss) v0.12.0                 arch=windows amd64 build= commit= runtime=go1.15.5
[2021/03/08 - 18:43:28]  INFO Config file detected                          path=C:\Users\User/AppData/Roaming/Ledger Live/lss.json
[2021/03/08 - 18:43:28]  INFO Warming up...
[2021/03/08 - 18:43:28] FATAL Failed to initialize Bus                      error=failed to load wallet: -4: Wallet file verification failed. Refusing to load database. Data file '/home/bitcoin/.bitcoin/satstack/wallet.dat' is already loaded.
```

Since ... recently bitcoind has automatically loaded used wallets... I believe.  

Currently

```
listwallets
[
  "wallet.dat",
  "spectercc965c6d9e62fa00/simple_",
  "satstack"
]
```
This isn't even an error, just confirmation that the desired state exists.  Any chance this could be addressed please.

**Comment by crackozark** [comment]
A couple of questions after failed connetivities to local network's running full nodes. 
#1. Ledger's satstack only bridge/scan for bitcoin wallets. One can't expect any operation for the litecoin network... is that correct? 
#2. After a failed attempt, need to 'add ccounts'from Manager to re-sync to show  any ballance on the account... which leads me to assert that one advantage of a successful syncing of full node is óff-line ( or one's own network ) transactions? Can someone re-interate what are pros and cons for those experimental features there? thanks...

**Comment by timdodge** [comment]
I'm having the same issue - I need to run
`bitcoin-cli unloadwallet "satstack"`
before starting lss

**Comment by samsong** [comment]
Same issue.

Launching LSS for 2nd time.
INFO config file detected path=/home/user/.config/Ledger Live/lss.json
FATAL Failed to initialize bus
error=failed to load wallet: -4: wallet file verification failed. Refusing to load database. Data file '/bitcoin/.bitcoin/satstack/wallet.dat' is already loaded

**Comment by jvandenbroek** [comment]
> I'm having the same issue - I need to run
> `bitcoin-cli unloadwallet "satstack"`
> before starting lss

Thanks, putting this RPC command as ExecStartPre in my lss systemd service file actually works around this issue. Of course this should not be necessary to do.

**Comment by samsong** [comment]
> > I'm having the same issue - I need to run
> > `bitcoin-cli unloadwallet "satstack"`
> > before starting lss
> 
> Thanks, putting this RPC command as ExecStartPre in my lss systemd service file actually works around this issue. Of course this should not be necessary to do.

agree this could be run inside lss if necessary to automate for users.

**Comment by autumnwakefield** [comment]
How do we run bitcoin-cli unloadwallet "satstack"? I run a rode with a raspberry pi and don't have access to run the script on the node.

**Comment by yasuoiwakura** [comment]
Same issue. reproduce:

run bitcoind until current blockheight is reached
connect using ./lss
at 3% of indexing, run out of disk space, resize partition reboot, restart bitcoind
./lss will pretend "wallet satstack is already loaded"

current workaround:
setup bitcoin-cli for rpc/local use and
run bitcoin-cli unloadwallet „satstack“
restart ./lss
