### ISSUE TITLE
manual set up using scripts/getdescriptor no longer works: force version of construct in requirements.txt

### ISSUE THREAD

**Issue by cybern0id** [LedgerHQ/satstack#50]
I've already reported this at [ledgerctl issue tracker](https://github.com/LedgerHQ/ledgerctl/issues/17) but thought I should mention it here in case anyone having the same problem needs a quick solution.

With recent release of construct version 2.10.63, `scripts/getdescriptor` no longer works. Solution (until ledgerwallet python library is fixed) is to change `scripts/requirements.txt` to force version 2.10.61.
```
:~$cat scripts/requirements.txt
base58
click
construct==2.10.61
ecdsa
ledgerwallet
protobuf
```

**Comment by adrienlacombe-ledger** [comment]
hi @cybern0id this is now fixed in ledgerctl
