### ISSUE TITLE
LedgerLive only asks to "unlock" 1 of 2 hardware wallets when adding self node?

### ISSUE THREAD

**Issue by samsong** [LedgerHQ/satstack#55]
I have 2 ledger hardware wallets loaded in ledger live.

when setup a new node, ledger ask me to unlock wallet.
If I unlock just 1 wallet ledger live says success & add the node.

What about my second hardware wallet? Why it didn't ask for that?
Seem like satstack only support 1 hardware wallet?

**Comment by adrienlacombe-ledger** [comment]
hey hi @samsong you would need to edit the lss.json file manually with the xpubs from both Nanos in your scenario.
