### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by samsong** [LedgerHQ/satstack#59]
Hello development team
Can you please advise us if you are still maintaining this project or if Ledger HQ is still putting support to this?
There has been no release since december 2020
no real comments on the recent issues raised like my one #54 

Should we abandon trying to use this?

**Comment by xanoni** [comment]
The complication is probably that the [practically sole](https://github.com/LedgerHQ/satstack/graphs/contributors) author has left Ledger and [now writes code for Brave browser](https://twitter.com/onybose) instead ...

https://blog.ledger.com/satstack/

**Comment by adrienlacombe-ledger** [comment]
Hi, maintenance is resuming, only caveat right now is that you need Bitcoin Nano app 1.6.5 to make it work, we are working on making this work with 2+
