### ISSUE TITLE
ERROR worker: Failed while importing descriptors

### ISSUE THREAD

**Issue by SkanderHelali** [LedgerHQ/satstack#75]
Howdy,

Having issues running this in the following environment:

* OpenSUSE Tumbleweed.
* Bitcoin Core: v23.0 (snap):
-server=1; disablewallet not set; txindex enabled.

Config is generated from the latest Ledger Live AppImage and the device is running the latest Bitcoin Nano app (2.x).

lss is able to communicate with the node. Runs the circulating supply check. I can see the satstack wallet being loaded in the Qt gui (but appears blank).
Once the circulating supply check is complete, the following error is printed and lss quits:

```
[2022/08/12 - 19:51:32]  INFO worker: #RunTheNumbers successful                     actualSupply=19119485.92676553 BTC expectedSupply=19119693.75 BTC height=749151

[2022/08/12 - 19:51:32] ERROR worker: Failed while importing descriptors            error=-4: This type of wallet does not support this command

[2022/08/12 - 19:51:32]  INFO Shutdown server: in progress          
       
[2022/08/12 - 19:51:32] ERROR Failed to query status                        err=bitcoind unreachable: -18: Requested wallet does not exist or is not loaded

[GIN] 2022/08/12 - 19:51:32 | 200 |     1.65613ms |       127.0.0.1 | GET      "/blockchain/v3/explorer/status"

[2022/08/12 - 19:51:32]  INFO Unloaded wallet successfully                  wallet=satstack

[2022/08/12 - 19:51:32]  INFO Shutdown server: done
```

Any idea?
Attempted removing the taproot descriptors from the generated config thinking that might the issue, same result.

**Comment by adrienlacombe-ledger** [comment]
Yeah, this is probably due to missing taproot support, I am working on it.

**Comment by adrienlacombe-ledger** [comment]
hi @SkanderHelali I released 0.16.0 this morning, it might work better now, can you please give it a try? thank you vm

**Comment by bscameheorn** [comment]
I am also receiving this error when trying to connect satstack to LedgerLive. 

[GIN] 2022/08/16 - 17:41:38 |←[97;42m 200 ←[0m|            0s |       127.0.0.1 |←[97;44m GET     ←[0m "/blockchain/v3/explorer/status"
[GIN] 2022/08/16 - 17:41:39 |←[97;42m 200 ←[0m|            0s |       127.0.0.1 |←[97;44m GET     ←[0m "/blockchain/v3/explorer/status"
[GIN] 2022/08/16 - 17:41:40 |←[97;42m 200 ←[0m|            0s |       127.0.0.1 |←[97;44m GET     ←[0m "/blockchain/v3/explorer/status"
←[0;90m[2022/08/16 - 17:41:41]←[0m ←[0;32m INFO←[0m←[0;36m worker:←[0m #RunTheNumbers successful                     ←[0;32mactualSupply←[0m=xxx.xxx BTC ←[0;32mexpectedSupply←[0m=xxx.xxx BTC ←[0;32mheight←[0m=749750
[GIN] 2022/08/16 - 17:41:41 |←[97;42m 200 ←[0m|      6.6159ms |       127.0.0.1 |←[97;44m GET     ←[0m "/blockchain/v3/explorer/status"
←[0;90m[2022/08/16 - 17:41:41]←[0m ←[0;31mERROR←[0m err -4: importdescriptors is not available for non-descriptor wallets
←[0;90m[2022/08/16 - 17:41:41]←[0m ←[0;31mERROR←[0m←[0;36m worker:←[0m Failed while importing descriptors            ←[0;31merror←[0m=-4: importdescriptors is not available for non-descriptor wallets
←[0;90m[2022/08/16 - 17:41:41]←[0m ←[0;31mFATAL←[0m←[0;36m worker:←[0m Failed to send INTERRUPT signal               ←[0;31merror←[0m=not supported by windows ←[0;31mpid←[0m=29168

**Comment by bscameheorn** [comment]
Also, I am using 0.16.0

**Comment by adrienlacombe-ledger** [comment]
I guess I know what's going on... do you know how to delete the satstack wallet on your bitcoin node? Satstack will re-create differently and it should work fine.

**Comment by SkanderHelali** [comment]
@adrienlacombe-ledger  Sorry for the delay, rescan took a while with birthday not set.
Tested on 0.16.0 and the issue seems to be fixed. Was able to import/scan all accounts and use them in Ledger Live. 👍🏻 
Thanks!

I'll leave this open for bscameheorn.

**Comment by adrienlacombe-ledger** [comment]
Excellent @SkanderHelali ! Thank you :)

**Comment by bscameheorn** [comment]
Worked, thank you!!

**Comment by adrienlacombe-ledger** [comment]
Excellent news!

**Comment by bscameheorn** [comment]
I am unsure why, but I am stuck in a loop in LedgerLive and satstack on Status: x% Account scan in progress ... It just keeps going from 100% to 0% after I delete my wallet, and delete all data in LedgerLive on windows and in bitcoin-gui it shows Rescanning and transactions are there. Do you have any ideas why?

**Comment by SkanderHelali** [comment]
> I am unsure why, but I am stuck in a loop in LedgerLive and satstack on Status: x% Account scan in progress ... It just keeps going from 100% to 0% after I delete my wallet, and delete all data in LedgerLive on windows and in bitcoin-gui it shows Rescanning and transactions are there. Do you have any ideas why?

It will take a very long time if you don't set a birthday in the generated config file. Ledger live doesn't seem to ask/set one.
Rescanning 10 accounts for every script type, from 2013 (default) to today - you'll see that "Account scan" loop for quite a while.

It will finish if you don't interrupt it, eventually. 
You're better off defining the birthday in the config for each account. (YYYY/MM/DD format)

**Comment by adrienlacombe-ledger** [comment]
thank you @SkanderHelali , indeed @bscameheorn depending on your hardware it can take a long time, not great that the loop restarts though I agree.
