### ISSUE TITLE
Wallet file verification failed

### ISSUE THREAD

**Issue by dannuttall** [LedgerHQ/satstack#89]
Originally Satstack was running fine and got to 95% complete on the scan. Then connection to my node was lost (unsure why). I then tried to restart the process, but keep getting the following error:

`Wallet file verification failed. SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another instance of Bitcoin Core?`

Nothing else is connected to my node so I'm unsure what to do to get passed this. Any ideas?

**Comment by adrienlacombe-ledger** [comment]
hi @dannuttall you can try `./satstack --unload-wallet` or otherwise just restart your bitcoin node

**Comment by adrienlacombe-ledger** [comment]
nice!
